export const cartActions = {
    SAVE_PRODUCT: 'SAVE_PRODUCT',
    SAVE_PRODUCT_SUCCESS: 'SAVE_PRODUCT_SUCCESS',
    SAVE_PRODUCT_ERROR: 'SAVE_PRODUCT_ERROR',

    LOAD_SAVE_PRODUCT: 'LOAD_SAVE_PRODUCT',
    LOAD_SAVE_PRODUCT_SUCCESS: "LOAD_SAVE_PRODUCT_SUCCESS",
    LOAD_SAVE_PRODUCT_ERROR: "LOAD_SAVE_PRODUCT_ERROR",

    DELETE_PRODUCT: 'DELETE_PRODUCT',
    DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
    DELETE_PRODUCT_ERROR: "DELETE_PRODUCT_ERROR",
};